#include "globals.h"
#include "GarrysMod/Lua/Interface.h"

#ifndef LUA_FUNCTIONS_H
#define LUA_FUNCTIONS_H

using namespace GarrysMod::Lua;

#define LUA_FUNCTION_HEADER(FUNC) int FUNC( lua_State* L )
 
// Channel states
#define LUAENUM_CHANNEL_STOPPED 0
#define LUAENUM_CHANNEL_PLAYING 1
#define LUAENUM_CHANNEL_PAUSED 2
#define LUAENUM_CHANNEL_STALLED 3

// FFT modes
#define LUAENUM_FFT_256 0
#define LUAENUM_FFT_512 1
#define LUAENUM_FFT_1024 2
#define LUAENUM_FFT_2048 3
#define LUAENUM_FFT_4096 4
#define LUAENUM_FFT_8192 5
#define LUAENUM_FFT_16384 6
#define LUAENUM_FFT_32768 7

// Custom FFT modes 
#define LUAENUM_FFT_16 10
#define LUAENUM_FFT_32 11
#define LUAENUM_FFT_64 12
#define LUAENUM_FFT_128 13

// Play modes
#define LUAENUM_MODE_NONE 0x00
#define LUAENUM_MODE_3D 0x01
#define LUAENUM_MODE_LOOP 0x02
#define LUAENUM_MODE_MONO 0x04
#define LUAENUM_MODE_NOPLAY 0x08
#define LUAENUM_MODE_NOBLOCK 0x10

// Tag types
#define LUAENUM_TAG_META 0
#define LUAENUM_TAG_HTTP 1
#define LUAENUM_TAG_ICY 2
#define LUAENUM_TAG_ID3 3
#define LUAENUM_TAG_MF 4
#define LUAENUM_TAG_MP4 5
#define LUAENUM_TAG_APE 6
#define LUAENUM_TAG_OGG 7

namespace LUAFUNC
{
	LUA_FUNCTION_HEADER(PullPendingChannels);

	namespace _G
	{
		namespace BASS3
		{
			LUA_FUNCTION_HEADER(PlayFile);
			LUA_FUNCTION_HEADER(PlayURL);
			LUA_FUNCTION_HEADER(CreateChannel);
			LUA_FUNCTION_HEADER(DecodeError);

			LUA_FUNCTION_HEADER(SetAgent);
			LUA_FUNCTION_HEADER(GetAgent);
			LUA_FUNCTION_HEADER(SetProxy);
			LUA_FUNCTION_HEADER(GetProxy);

			LUA_FUNCTION_HEADER(GetEAX);
			LUA_FUNCTION_HEADER(SetEAX);
		}
	}

	namespace _R
	{
		namespace IBASS3Channel
		{
			LUA_FUNCTION_HEADER(lua__gc);
			LUA_FUNCTION_HEADER(lua__eq);
			LUA_FUNCTION_HEADER(lua__tostring);

			LUA_FUNCTION_HEADER(Remove);
			LUA_FUNCTION_HEADER(IsValid);

			LUA_FUNCTION_HEADER(PlayFile);
			LUA_FUNCTION_HEADER(PlayURL);

			LUA_FUNCTION_HEADER(Play);
			LUA_FUNCTION_HEADER(Stop);
			LUA_FUNCTION_HEADER(Pause);

			LUA_FUNCTION_HEADER(GetState);

			LUA_FUNCTION_HEADER(SetVolume);
			LUA_FUNCTION_HEADER(GetVolume);
			LUA_FUNCTION_HEADER(SetVolumeBoost);
			LUA_FUNCTION_HEADER(GetVolumeBoost);
			LUA_FUNCTION_HEADER(VolumeFadeTo);
			LUA_FUNCTION_HEADER(VolumeIsFading);

			LUA_FUNCTION_HEADER(SetBalance);
			LUA_FUNCTION_HEADER(GetBalance);
			LUA_FUNCTION_HEADER(BalanceFadeTo);
			LUA_FUNCTION_HEADER(BalanceIsFading);

			LUA_FUNCTION_HEADER(Is3D);
			LUA_FUNCTION_HEADER(IsLooping);
			LUA_FUNCTION_HEADER(IsOnline);
			LUA_FUNCTION_HEADER(IsBlockStreamed);

			LUA_FUNCTION_HEADER(EnableLooping);
			LUA_FUNCTION_HEADER(FFT);
			LUA_FUNCTION_HEADER(FFTComplex);
			LUA_FUNCTION_HEADER(GetLevel);

			LUA_FUNCTION_HEADER(GetTime);
			LUA_FUNCTION_HEADER(SetTime);

			LUA_FUNCTION_HEADER(GetLength);
			LUA_FUNCTION_HEADER(IsEndless);

			LUA_FUNCTION_HEADER(IsSeeking);

			LUA_FUNCTION_HEADER(GetTag);
			LUA_FUNCTION_HEADER(GetFileName);
			LUA_FUNCTION_HEADER(GetFileFormat);

			LUA_FUNCTION_HEADER(GetSamplingRate);
			LUA_FUNCTION_HEADER(GetBitsPerSample);
			LUA_FUNCTION_HEADER(GetAverageBitRate);

			LUA_FUNCTION_HEADER(GetPos);
			LUA_FUNCTION_HEADER(SetPos);

			LUA_FUNCTION_HEADER(Get3DFadeDistance);
			LUA_FUNCTION_HEADER(Set3DFadeDistance);

			LUA_FUNCTION_HEADER(Get3DCone);
			LUA_FUNCTION_HEADER(Set3DCone);

			LUA_FUNCTION_HEADER(Get3DEnabled);
			LUA_FUNCTION_HEADER(Set3DEnabled);

			LUA_FUNCTION_HEADER(GetEAXmix);
			LUA_FUNCTION_HEADER(SetEAXmix);
		}
	}
}

#endif